config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :gifs
  resources :users, only: [:show]

  get '*tag', to: 'gifs#random', as: :random_gif # this maps any tag to random action

  root to: 'gifs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gif.rb
class Gif < ApplicationRecord
  include ImageUploader::Attachment(:image)
  belongs_to :user

  acts_as_taggable

  scope :sorted, -> { order(created_at: :desc) } # sort by the most recent when using the sorted method

  def self.random
    order('RANDOM()').first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_person_name
  has_many :gifs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_paramenters, if: :devise_controller?

  protected

  def configure_permitted_paramenters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_gif, only: %i[edit update destroy]

  # GET /gifs or /gifs.json
  def index
    @gifs = Gif.includes(:tags, :user).sorted
  end

  # GET /gifs/1 or /gifs/1.json
  def show
    @gif = Gif.find(params[:id])
  end

  def random
    @gif = Gif.tagged_with(params[:tag]).random # controler method to grab random gifs
    @gif ||= Gif.random
    render :show
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
  end

  # GET /gifs/1/edit
  def edit
  end

  # POST /gifs or /gifs.json
  def create
    @gif = current_user.gifs.new(gif_params)

    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: "Gif was successfully created." }
        format.json { render :show, status: :created, location: @gif }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifs/1 or /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: "Gif was successfully updated." }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1 or /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: "Gif was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

   # Use callbacks to share common setup or constraints between actions.
   def set_gif
     @gif = current_user.gifs.find(params[:id])
   end

   # Only allow a list of trusted parameters through.
   def gif_params
     params.require(:gif).permit(:image, :tag_list)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    redirect_to root_path
  end

  def show
    @gifs = @user.gifs.includes(:tags, :user).sorted
    render 'gifs/index'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
  def linked_tag_list(gif)
    list = gif.tags.map do |tag|
      link_to tag.name, random_gif_path(tag: tag.name) # random_gif means that the url for the tags will be /tag and not /tag="something" at the url
    end

    safe_join list, ', ' # this will join the html links by comman and render as HTML
  end

  def full_gif_url(gif)
    gif.image_url(host: request.protocol + request.host_with_port)
  end

end

app/views/gifs/_form.html.erb
<%= form_with(model: gif) do |form| %>
  <% if gif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gif.errors.count, "error") %> prohibited this gif from being saved:</h2>

      <ul>
        <% gif.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


   <div class="field">
    <% if form.object.persisted? %>
      <%= image_tag form.object.image_url %>
      <% else %>
     <%= form.label :image %>
     <%= form.hidden_field :image, value: form.object.cached_image_data %>
     <%= form.file_field :image, class: "form-control" %>
   </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_list, "Tag list (comma separated)"%>
    <%= form.text_field :tag_list, value: form.object.tag_list.join(", "), class: "form-control"%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-purple" %>
  </div>
<% end %>

app/views/gifs/edit.html.erb
<div class="max-w-xs mx-auto">
  <h1 class="text-4xl mb-5">Edit</h1>

<%= render 'form', gif: @gif %>

<%= link_to 'Destroy', @gif, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Show', @gif %> |
<%= link_to 'Back', gifs_path %>
</div>

app/views/gifs/index.html.erb
<div class="container flex mx-auto mt-10 flex-wrap justify-center">
<% @gifs.each do |gif| %>
  <div class="w-64 m-2 border rounded shadow">
    <%= link_to image_tag(gif.image_url, class: "mx-auto"), gif, class: "block bg-black"%>
    <div class="p-2 text-center">
      <div> Uploaded by <%= link_to gif.user.name, gif.user %></div>
      <%= linked_tag_list gif %>      
    </div>
  </div>
<% end %>
</div>

app/views/gifs/new.html.erb
<div class="max-w-xs mx-auto">
  <h1 class="text-4xl mb-5">New Gif</h1>

  <%= render 'form', gif: @gif %>

  <%= link_to 'Back', gifs_path %>
</div>

app/views/gifs/show.html.erb
<div class="w-64 mx-auto mt-10">
  <%= image_tag @gif.image_url, class: "mx-auto" %>

<div class="flex justify-between text-xs my-2">
<div> Uploaded by <%= link_to @gif.user.name, @gif.user %></div>
  <div>
    <% if user_signed_in? && current_user == @gif.user %>
      <%= link_to 'Edit', edit_gif_path(@gif) %>
    <% end %>
  </div>
</div>

<div class="flex text-xs" data-controller="clipboard">
  <%= text_field_tag nil, full_gif_url(@gif), data: { target: 'clipboard.source' }, class: "form-control rounded-l" %>
  <button data-action="click->clipboard#copy" data-target="clipboard.button" class="btn btn-purple rounded-r" >Copy</button>
</div>

<div class="text-center text-sm mt-4">
  <%= linked_tag_list @gif %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="bg-gray-800 antialiased">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>AnimatedGif</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/navbar" %>

    <div class="mt-10">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="flex bg-white border-b border-gray-200 z-100 h-16 items-center">
  <div class="w-full max-w-screen-xl relative mx-auto px-6">
    <div class="flex items-center -mx-6">


      <div class="flex-grow">
        <div class="flex items-center">
          <%= link_to "AnimatedGif.me", root_path, class: "block lg:mr-4" %>
        </div>
      </div>
      <div>
      <%= link_to 'New Gif', new_gif_path %>
      
        <% if user_signed_in? %>
          <%= link_to "Account", edit_user_registration_path %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %>
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<p>
    <%= link_to 'Gifs', root_path %>
      
    
    </p>